using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace ClientesPeto.Infrastructure.Scaffold
{
    public partial class CatprodSicavi
    {
        public string Cveprod { get; set; }
        public string Desprod { get; set; }
        public DateTime Fecalta { get; set; }
        public string Cveuni { get; set; }
        public int Cvefam { get; set; }
        public int Cvemar { get; set; }
        public string Desmod { get; set; }
        public string Desubi { get; set; }
        public bool Tipprod { get; set; }
        public bool Edoprod { get; set; }
        public bool Paqprod { get; set; }
        public string Codbar { get; set; }
        public int Numobj { get; set; }
        public string Observa { get; set; }
        public byte[] Foto { get; set; }
        public DateTime Fecmodprec { get; set; }
        public decimal Lispre1 { get; set; }
        public decimal Lispre2 { get; set; }
        public decimal Lispre3 { get; set; }
        public decimal Lispre4 { get; set; }
        public decimal Lispre5 { get; set; }
        public decimal Lispre6 { get; set; }
        public decimal Minprod { get; set; }
        public decimal Maxprod { get; set; }
        public string Cveprodprov { get; set; }
        public bool Manserie { get; set; }
        public bool Mankilom { get; set; }
        public bool Manrenta { get; set; }
        public decimal Diaini1 { get; set; }
        public decimal Diafin1 { get; set; }
        public decimal Diatoler1 { get; set; }
        public decimal Diaprec1 { get; set; }
        public decimal Diaini2 { get; set; }
        public decimal Diafin2 { get; set; }
        public decimal Diatoler2 { get; set; }
        public decimal Diaprec2 { get; set; }
        public decimal Diaini3 { get; set; }
        public decimal Diafin3 { get; set; }
        public decimal Diatoler3 { get; set; }
        public decimal Diaprec3 { get; set; }
        public decimal Diaini4 { get; set; }
        public decimal Diafin4 { get; set; }
        public decimal Diatoler4 { get; set; }
        public decimal Diaprec4 { get; set; }
        public bool Displun { get; set; }
        public bool Dispmar { get; set; }
        public bool Dispmie { get; set; }
        public bool Dispjue { get; set; }
        public bool Dispvie { get; set; }
        public bool Dispsab { get; set; }
        public bool Dispdom { get; set; }
        public decimal Kilommantto { get; set; }
        public decimal Rentasmantto { get; set; }
        public decimal Numsemmantto { get; set; }
        public DateTime Fechareal { get; set; }
        public string Login { get; set; }
        public decimal Factoractprecio { get; set; }
        public decimal Fleteactprecio { get; set; }
        public string Codbar2 { get; set; }
        public string Codbar3 { get; set; }
        public string Codbar4 { get; set; }
        public bool Impcodbarpos { get; set; }
        public decimal Factoractprecio2 { get; set; }
        public decimal Factoractprecio3 { get; set; }
        public decimal Factoractprecio4 { get; set; }
        public decimal Factoractprecio5 { get; set; }
        public decimal Factoractprecio6 { get; set; }
        public bool Detalle { get; set; }
        public bool Listado1 { get; set; }
        public bool Listado2 { get; set; }
        public bool Listado3 { get; set; }
        public bool Listado4 { get; set; }
        public decimal PrecioAdic { get; set; }
        public bool Listado5 { get; set; }
        public decimal Casco { get; set; }
        public decimal Asientos { get; set; }
        public decimal Respaldos { get; set; }
        public decimal Otros1 { get; set; }
        public decimal Otros2 { get; set; }
        public decimal PrecioAdic2 { get; set; }
        public bool ListadoCol1 { get; set; }
        public bool ListadoCol2 { get; set; }
        public bool Listado6 { get; set; }
        public decimal Otros3 { get; set; }
        public bool ListadoCol3 { get; set; }
        public bool Tienda { get; set; }
        public bool Mayoreo { get; set; }
        public decimal ColorMad1 { get; set; }
        public decimal ColorMad2 { get; set; }
        public decimal ColorMad3 { get; set; }
        public bool Caducidad { get; set; }
        public byte NivelControl { get; set; }
        public int Cvemov { get; set; }
        public int NTipoPrecio { get; set; }
        public int NCantDesc { get; set; }
        public string Categoria { get; set; }
        public int BimAplicado { get; set; }
        public DateTime? FecUltHorChg { get; set; }
        public decimal Precio1Ori { get; set; }
        public string HistBimChg { get; set; }
        public int? EmpSucOri { get; set; }
        public string EmpLoteEnaj { get; set; }
        public long EmpFolBoleta { get; set; }
        public int EmpFolIndice { get; set; }
        public DateTime? EmpFecPres { get; set; }
        public double EmpMontEval { get; set; }
        public double EmpMontPres { get; set; }
        public double EmpMontInte { get; set; }
        public double EmpPlazo { get; set; }
        public int EmpDiasPlazo { get; set; }
        public string EmpDescPlazo { get; set; }
        public double EmpTasa { get; set; }
        public int EmpRefrendos { get; set; }
        public string EmpLogin { get; set; }
        public string EmpValuador { get; set; }
        public double EmpPagoCapital { get; set; }
        public double EmpInteresPagado { get; set; }
        public double EmpRecargoPagado { get; set; }
        public int EmpSaldo { get; set; }
        public bool PrecioDef { get; set; }
        public decimal PorcDesc { get; set; }
        public string CveUserResp { get; set; }
        public string CveUserGte { get; set; }
        public string EdoFisico { get; set; }
        public double EmpInteres { get; set; }
        public double EmpRecargo { get; set; }
        public int EmpCosFinDias { get; set; }
        public double EmpCosFin { get; set; }
    }
}
